### ISSUE TITLE
bin rate in binning

### ISSUE THREAD

**Issue by Spencerai** [Sundar0989/XuniVerse#1]
can supply a parameter to control each category rate of the train samples?
Because when the category  rate is  very few,the binning will be meaningless.

**Comment by Sundar0989** [comment]
Please use the custom binning feature to supply bins for variables. Here is the notes from documentation.

```custom_binning: dict (default=None)
    Dictionary structure - {'feature_name': float list}
    Example - {'age': [0., 1., 2., 3.]}
    Using this parameter, the user can perform custom binning on variables. This parameter is also used to apply previously computed bins for each feature (Score new data). ```
