### ISSUE TITLE
Continuous outcome

### ISSUE THREAD

**Issue by raheems** [Sundar0989/XuniVerse#2]
Is it possible to use continuous outcome variable?

**Comment by Davisy** [comment]
I have tried with the continuous outcome is not working, the errors stated that target "y" should have 2 unique values (classification problem).

**Comment by raheems** [comment]
> I have tried with the continuous outcome is not working, the errors stated that target "y" should have 2 unique values (classification problem).

The author said on Mediam post that currently only classification problem is supported.

**Comment by Davisy** [comment]
> > I have tried with the continuous outcome is not working, the errors stated that target "y" should have 2 unique values (classification problem).
> 
> The author said on Medium post that currently only classification problem is supported.

I hope is for both binary and Multiclass classification

**Comment by Sundar0989** [comment]
Currently, it can only handle Binary outcome. The next version, I will plan to release Multiclass classification support.
